version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - ./html:/var/www/html
      - ./script:/var/www/html/my_script/
    #restart: always
    container_name: expim-web
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "expim"
      MYSQL_DATABASE: "wp"
      MYSQL_USER: "expim"
      MYSQL_PASSWORD: "expim"
    volumes:
      - /data/mysql:/var/lib/mysql
    container_name: expim-db
    restart: always
volumes:
  app:
  dbData: