- name: Create virtual Ubuntu Server
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create virtual machine
      virtualbox_guest:
        name: expim-vm
        state: present
        os_type: Ubuntu_64
        memory: 4096
        cpus: 2
        disk_size: 35000
        iso_path: d:\iso\ubuntu-22.04.1-live-server-amd64.iso
        port_forwarding:
          - hostport: 80
            guestport: 80
          - hostport: 2222
            guestport: 22
        username: expim
        password: expim
    - name: Install openssh, docker, git
      become: true
      apt:
        name:
          - openssh-server
          - docker.io
          - git
        state: present
    - name: Add key to authorized_keys
      authorized_key:
        user: centurion
        key: "{{ lookup('file', 'id_rsa.pub') }}"
    - name: Clone repository
      git:
        repo: https://github.com/YaCenturion/Expim-test.git
        dest: /home/expim/job
